In [2]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

c:\Users\aarni\anaconda3\envs\vero\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
# 1️⃣ Fix separator
# 2️⃣ Fix encoding
# 3️⃣ Fix decimal symbols
# 4️⃣ Parse dates
# 5️⃣ Convert numeric columns

In [5]:
df = pd.read_csv("Transactions2.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'Transactions2.csv'

In [7]:
import os
os.getcwd()

'c:\\Users\\aarni\\OneDrive\\Työpöytä\\Python_data_project\\vero.py'

In [7]:
df = pd.read_csv(
    "C:/Users/aarni/Downloads/Transactions.csv",
    sep=",",
    encoding="latin1"
)
df

,ï»¿PÃÂ¤ivÃÂ¤ys,Aika,Tuote,ISIN,Reference exchange,Venue,Quantity,Kurssi,Unnamed: 8,Markkina-arvo,Unnamed: 10,Value EUR,Vaihtokurssi,AutoFX Fee,Transaction and/or third party fees EUR,Kokonaissumma EUR,Order ID,Unnamed: 17
0,"17-12-2025,15:04,ROLLS-ROYCE HOLDINGS PLC,GB00...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"16-12-2025,11:39,VANGUARD FTSE ALL-WORLD UCITS...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"17-11-2025,11:18,DRONESHIELD LTD,AU000000DRO2,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"14-11-2025,11:20,AIRBUS SE,NL0000235190,XET,XE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"12-11-2025,18:51,ADOBE INC,US00724F1012,NDQ,XN...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181,"23-01-2025,15:53,APPLE INC,US0378331005,NDQ,CD...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182,"23-01-2025,12:31,INVISIO AB,SE0001200015,OMX,M...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
183,"23-01-2025,12:31,INVISIO AB,SE0001200015,OMX,X...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
184,"06-01-2025,00:00,SONO GROUP NV,NL0015000N74,OT...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
185,"06-01-2025,00:00,SONO GROUP NV,NL0015002AM0,OT...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df = pd.read_csv('Transactions2.csv', index_col=0)

In [11]:
df.columns

Index(['Aika', 'Tuote', 'ISIN', 'Reference exchange', 'Venue', 'Quantity',
       'Kurssi', 'Unnamed: 8', 'Markkina-arvo', 'Unnamed: 10', 'Value EUR',
       'Vaihtokurssi', 'AutoFX Fee', 'Transaction and/or third party fees EUR',
       'Kokonaissumma EUR', 'Order ID', 'Unnamed: 17'],
      dtype='str')

In [14]:
df.head()

,Aika,Tuote,ISIN,Reference exchange,Venue,Quantity,Kurssi,Unnamed: 8,Markkina-arvo,Unnamed: 10,Value EUR,Vaihtokurssi,AutoFX Fee,Transaction and/or third party fees EUR,Kokonaissumma EUR,Order ID,Unnamed: 17
Päiväys,,,,,,,,,,,,,,,,,
17-12-2025,15:04,ROLLS-ROYCE HOLDINGS PLC,GB00B63H8491,LSE,XLON,70,"1124,5000",GBX,"−78715,00",GBX,"−896,22","87,8302","−2,24","−4,90","−901,12",NaN,ace9180b-cee6-4d82-8b10-b9ba32132ec3
16-12-2025,11:39,VANGUARD FTSE ALL-WORLD UCITS - (USD) ACCUMULA...,IE00BK5BQT80,XET,XETA,−6,"142,9200",EUR,"857,52",EUR,"857,52",NaN,"0,00","−3,00","854,52",NaN,b903c431-a183-4acb-a822-12d44962a865
17-11-2025,11:18,DRONESHIELD LTD,AU000000DRO2,TDG,XGAT,220,"1,5660",EUR,"−344,52",EUR,"−344,52",NaN,"0,00","−3,90","−348,42",NaN,d4da0833-e7b2-4af2-a7a5-ed5cc9c33c50
14-11-2025,11:20,AIRBUS SE,NL0000235190,XET,XETA,8,"204,4000",EUR,"−1635,20",EUR,"−1635,20",NaN,"0,00","−4,90","−1640,10",NaN,aab4cdea-3051-4458-8fb3-2aef578b1731
12-11-2025,18:51,ADOBE INC,US00724F1012,NDQ,XNAS,−5,"337,1000",USD,"1685,50",USD,"1454,03","1,1592","−3,64","−2,00","1452,03",NaN,109af4c0-599f-4abb-a263-c292853a5f34

In [16]:
print(df[["Quantity", "Kurssi", "Kokonaissumma EUR", "AutoFX Fee", "Transaction and/or third party fees EUR"]].dtypes)

Quantity                                   str
Kurssi                                     str
Kokonaissumma EUR                          str
AutoFX Fee                                 str
Transaction and/or third party fees EUR    str
dtype: object

In [ ]:
cols_to_convert = [
    "Quantity",
    "Kurssi",
    "Kokonaissumma EUR",
    "AutoFX Fee",
    "Transaction and/or third party fees EUR"
]

In [20]:
for col in cols_to_convert:
    df[col] = df[col].astype(str)  # Ensure string to apply replace
    df[col] = df[col].str.replace(".", "", regex=False)   # Remove thousand separators if present
    df[col] = df[col].str.replace(",", ".", regex=False)  # Convert decimal comma to dot

In [23]:
for col in cols_to_convert:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [24]:
df["AutoFX Fee"] = df["AutoFX Fee"].fillna(0)
df["Transaction and/or third party fees EUR"] = df["Transaction and/or third party fees EUR"].fillna(0)

In [39]:
print(df[["Quantity", "Kurssi", "Kokonaissumma EUR", "AutoFX Fee", "Transaction and/or third party fees EUR"]].dtypes)

Quantity                                   float64
Kurssi                                     float64
Kokonaissumma EUR                          float64
AutoFX Fee                                 float64
Transaction and/or third party fees EUR    float64
dtype: object

In [42]:
cols_to_fix = ["Value EUR", "AutoFX Fee", "Transaction and/or third party fees EUR", "Kokonaissumma EUR"]

def fix_european_number(s):
    if pd.isna(s):
        return s
    s = str(s)
    s = s.replace('\u2212', '-')  # Unicode minus → ASCII minus
    s = s.replace('\u2013', '-').replace('\u2014', '-')  # just in case
    s = s.replace('\xa0', '').replace(' ', '')  # remove spaces
    # Remove thousands separator dots (before changing decimal comma)
    s = s.replace('.', '')  
    # Replace decimal comma with dot
    s = s.replace(',', '.')
    return s

for col in cols_to_fix:
    df[col] = df[col].apply(fix_european_number)
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [43]:
df.head()

,Päiväys,Aika,Tuote,ISIN,Reference exchange,Venue,Quantity,Kurssi,Unnamed: 8,Markkina-arvo,Unnamed: 10,Value EUR,Vaihtokurssi,AutoFX Fee,Transaction and/or third party fees EUR,Kokonaissumma EUR,Order ID,Unnamed: 17
0,17-12-2025,15:04,ROLLS-ROYCE HOLDINGS PLC,GB00B63H8491,LSE,XLON,70.0,1124.500,GBX,"−78715,00",GBX,NaN,"87,8302",0,0,NaN,NaN,ace9180b-cee6-4d82-8b10-b9ba32132ec3
1,16-12-2025,11:39,VANGUARD FTSE ALL-WORLD UCITS - (USD) ACCUMULA...,IE00BK5BQT80,XET,XETA,NaN,142.920,EUR,"857,52",EUR,85752.0,NaN,0,0,85752.0,NaN,b903c431-a183-4acb-a822-12d44962a865
2,17-11-2025,11:18,DRONESHIELD LTD,AU000000DRO2,TDG,XGAT,220.0,1.566,EUR,"−344,52",EUR,NaN,NaN,0,0,NaN,NaN,d4da0833-e7b2-4af2-a7a5-ed5cc9c33c50
3,14-11-2025,11:20,AIRBUS SE,NL0000235190,XET,XETA,8.0,204.400,EUR,"−1635,20",EUR,NaN,NaN,0,0,NaN,NaN,aab4cdea-3051-4458-8fb3-2aef578b1731
4,12-11-2025,18:51,ADOBE INC,US00724F1012,NDQ,XNAS,NaN,337.100,USD,"1685,50",USD,145403.0,"1,1592",0,0,145403.0,NaN,109af4c0-599f-4abb-a263-c292853a5f34

In [61]:
# Step 1: Try reading with UTF-16 (common for Excel exports)
df_raw = pd.read_csv("Transactions2.csv", dtype=str, encoding='utf-16', sep=';')  # or 'utf-16le', try both

# Step 2: Inspect raw problematic cells
print(repr(df_raw.loc[0, 'Value EUR']))  # shows all invisible characters

# Step 3: Universal clean function
import re

def robust_parse_euro_number(s):
    if pd.isna(s):
        return 0.0
    s = str(s)
    # Keep only digits, minus, comma, dot
    s = re.sub(r'[^0-9,\-\.()]', '', s)
    # Convert parentheses to minus
    if s.startswith('(') and s.endswith(')'):
        s = '-' + s[1:-1]
    # Replace Unicode minus with ASCII minus
    s = s.replace('−', '-')
    # Remove thousands separator dots
    s = re.sub(r'\.(?=\d{3},)', '', s)
    # Replace decimal comma with dot
    s = s.replace(',', '.')
    # Convert to float
    try:
        return float(s)
    except:
        return 0.0

# Step 4: Apply to all relevant columns
cols_to_fix = ["Value EUR", "AutoFX Fee", "Transaction and/or third party fees EUR", "Kokonaissumma EUR"]

for col in cols_to_fix:
    df_raw[col] = df_raw[col].apply(robust_parse_euro_number)

df_raw["Kokonaissumma EUR"] = df_raw["Value EUR"] + df_raw["Transaction and/or third party fees EUR"]

# Check results
print(df_raw[cols_to_fix].head(20))

UnicodeDecodeError: 'utf-16' codec can't decode bytes in position 0-1: Stream does not start with BOM

In [62]:
df_raw = pd.read_csv("Transactions2.csv", dtype=str, encoding='cp1252', sep=';')  # use sep=';' if your file is semicolon-separated

In [71]:
df_raw.columns = [col.strip().replace('\xa0','') for col in df_raw.columns]

In [72]:
numeric_cols = ["Value EUR", "AutoFX Fee", "Transaction and/or third party fees EUR", "Kokonaissumma EUR"]

for col in numeric_cols:
    df_raw[col] = df_raw[col].apply(parse_euro_number)

# Recalculate totals
df_raw["Kokonaissumma EUR"] = df_raw["Value EUR"] + df_raw["Transaction and/or third party fees EUR"]

print(df_raw[numeric_cols].head(20))

KeyError: 'Value EUR'

In [ ]:
df.head()

,Päiväys,Aika,Tuote,ISIN,Reference exchange,Venue,Quantity,Kurssi,Unnamed: 8,Markkina-arvo,Unnamed: 10,Value EUR,Vaihtokurssi,AutoFX Fee,Transaction and/or third party fees EUR,Kokonaissumma EUR,Order ID,Unnamed: 17
0,17-12-2025,15:04,ROLLS-ROYCE HOLDINGS PLC,GB00B63H8491,LSE,XLON,70.0,1124.500,GBX,"−78715,00",GBX,NaN,"87,8302",0.0,0.0,NaN,NaN,ace9180b-cee6-4d82-8b10-b9ba32132ec3
1,16-12-2025,11:39,VANGUARD FTSE ALL-WORLD UCITS - (USD) ACCUMULA...,IE00BK5BQT80,XET,XETA,NaN,142.920,EUR,"857,52",EUR,857.52,NaN,0.0,0.0,857.52,NaN,b903c431-a183-4acb-a822-12d44962a865
2,17-11-2025,11:18,DRONESHIELD LTD,AU000000DRO2,TDG,XGAT,220.0,1.566,EUR,"−344,52",EUR,NaN,NaN,0.0,0.0,NaN,NaN,d4da0833-e7b2-4af2-a7a5-ed5cc9c33c50
3,14-11-2025,11:20,AIRBUS SE,NL0000235190,XET,XETA,8.0,204.400,EUR,"−1635,20",EUR,NaN,NaN,0.0,0.0,NaN,NaN,aab4cdea-3051-4458-8fb3-2aef578b1731
4,12-11-2025,18:51,ADOBE INC,US00724F1012,NDQ,XNAS,NaN,337.100,USD,"1685,50",USD,1454.03,"1,1592",0.0,0.0,1454.03,NaN,109af4c0-599f-4abb-a263-c292853a5f34

In [60]:
df.head()

,Päiväys,Aika,Tuote,ISIN,Reference exchange,Venue,Quantity,Kurssi,Unnamed: 8,Markkina-arvo,Unnamed: 10,Value EUR,Vaihtokurssi,AutoFX Fee,Transaction and/or third party fees EUR,Kokonaissumma EUR,Order ID,Unnamed: 17
0,17-12-2025,15:04,ROLLS-ROYCE HOLDINGS PLC,GB00B63H8491,LSE,XLON,70.0,1124.500,GBX,"−78715,00",GBX,896.22,"87,8302",2.24,4.9,901.12,NaN,ace9180b-cee6-4d82-8b10-b9ba32132ec3
1,16-12-2025,11:39,VANGUARD FTSE ALL-WORLD UCITS - (USD) ACCUMULA...,IE00BK5BQT80,XET,XETA,NaN,142.920,EUR,"857,52",EUR,857.52,NaN,0.00,3.0,860.52,NaN,b903c431-a183-4acb-a822-12d44962a865
2,17-11-2025,11:18,DRONESHIELD LTD,AU000000DRO2,TDG,XGAT,220.0,1.566,EUR,"−344,52",EUR,344.52,NaN,0.00,3.9,348.42,NaN,d4da0833-e7b2-4af2-a7a5-ed5cc9c33c50
3,14-11-2025,11:20,AIRBUS SE,NL0000235190,XET,XETA,8.0,204.400,EUR,"−1635,20",EUR,1635.20,NaN,0.00,4.9,1640.10,NaN,aab4cdea-3051-4458-8fb3-2aef578b1731
4,12-11-2025,18:51,ADOBE INC,US00724F1012,NDQ,XNAS,NaN,337.100,USD,"1685,50",USD,1454.03,"1,1592",3.64,2.0,1456.03,NaN,109af4c0-599f-4abb-a263-c292853a5f34